# Generated by Django 5.2.8 on 2026-01-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcustomer',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
