# Generated by Django 5.2.8 on 2026-03-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashsale',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
